### PR TITLE
File read with encoding try

### LINKED ISSUE #4: File encoding issue in tos_success input
The second and third items in #2 are not, after all, side effects of the first item. If an input file were exported as a CSV from Excel, it might be encoded as Mac Roman or Latin-1 (ISO-8859-1) rather than UTF-8 as might be expected. In this case, the WTH parsing fails out like so:

```
Traceback (most recent call last):
 File "/Users/kblock/hirise-tools/CIPP/tos_success.py", line 84, in <module>
   sys.exit(main())
 File "/Users/kblock/hirise-tools/CIPP/tos_success.py", line 62, in main
   for row in wthreader:
 File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
   (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 1268: invalid continuation byte
```

We can force the encoding on WTH read to `latin_1` or `mac_roman` and the file imports just fine.

### PR DESCRIPTION
**Pull request by SchallerSpace**
Address and nominally closes #4 and #5.

### CODE REVIEW

**Comment by SchallerSpace** [comment]
Not entirely sure what happens when you add a reviewer, but let's find out.

**Comment by rbeyer** [comment]
Okay, so I made some changes which you could rightly say were about what color to paint the bikeshed.  

I removed some length checks that you added, because they seemed incorrect.  The error messages said that they couldn't read the file, but the conditions to trigger those errors would only happen if the file was perfectly readable, but empty (because otherwise an exception would be thrown).  In either case a '0' would be shown in one or the other positions in the final print statement.  Even if they are zeroes, there isn't an error, as the program is working as intended, but the user has provided an empty file (which seems like a really, really narrow failure case).

**Review by rbeyer — COMMENTED** [review]
I think this could be a little more streamlined and pythonic.  Which resulted in my changes to the branch.

**Comment by SchallerSpace** [comment]
> Okay, so I made some changes which you could rightly say were about what color to paint the bikeshed.

:)

> I removed some length checks that you added, because they seemed incorrect. The error messages said that they couldn't read the file, but the conditions to trigger those errors would only happen if the file was perfectly readable, but empty (because otherwise an exception would be thrown). In either case a '0' would be shown in one or the other positions in the final print statement. Even if they are zeroes, there isn't an error, as the program is working as intended, but the user has provided an empty file (which seems like a really, really narrow failure case).

Agreed (that the error messages did not match the error conditions).

**Pull request merged**
